<a href="https://colab.research.google.com/github/omj3424/Python_Programming_Study/blob/main/pandas_exercises/03_Grouping/Regiment/Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regiment

### Introduction:

Special thanks to: http://chrisalbon.com/ for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [28]:
import pandas as pd

### Step 2. Create the DataFrame with the following values:

In [29]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'],
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

### Step 3. Assign it to a variable called regiment.
#### Don't forget to name each column

In [30]:
regiment = pd.DataFrame(data = raw_data)
regiment

      regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

### Step 4. What is the mean preTestScore from the regiment Nighthawks?

In [31]:
regiment[regiment['regiment'] == 'Nighthawks'].groupby('regiment')['preTestScore'].mean()

regiment
Nighthawks    15.25
Name: preTestScore, dtype: float64

### Step 5. Present general statistics by company

In [32]:
regiment.groupby('company').describe().stack()

# regiment.groupby('company').describe()

               preTestScore  postTestScore
company
1st     count      6.000000       6.000000
        mean       6.666667      57.666667
        std        8.524475      27.485754
        min        2.000000      25.000000
        25%        3.000000      34.250000
        50%        3.500000      66.000000
        75%        4.000000      70.000000
        max       24.000000      94.000000
2nd     count      6.000000       6.000000
        mean      15.500000      67.000000
        std       14.652645      14.057027
        min        2.000000      57.000000
        25%        2.250000      58.250000
        50%       13.500000      62.000000
        75%       29.250000      68.000000
        max       31.000000      94.000000

### Step 6. What is the mean of each company's preTestScore?

In [33]:
regiment.groupby('company')['preTestScore'].mean()

company
1st     6.666667
2nd    15.500000
Name: preTestScore, dtype: float64

### Step 7. Present the mean preTestScores grouped by regiment and company

In [34]:
regiment.groupby(['regiment', 'company'])['preTestScore'].mean()

regiment    company
Dragoons    1st         3.5
            2nd        27.5
Nighthawks  1st        14.0
            2nd        16.5
Scouts      1st         2.5
            2nd         2.5
Name: preTestScore, dtype: float64

### Step 8. Present the mean preTestScores grouped by regiment and company without heirarchical indexing

In [35]:
regiment.groupby(['regiment', 'company'])['preTestScore'].mean().unstack()

company      1st   2nd
regiment
Dragoons     3.5  27.5
Nighthawks  14.0  16.5
Scouts       2.5   2.5

### Step 9. Group the entire dataframe by regiment and company

In [37]:
regiment.groupby(['regiment', 'company'])[['preTestScore', 'postTestScore']].mean()

                    preTestScore  postTestScore
regiment   company
Dragoons   1st               3.5           47.5
           2nd              27.5           75.5
Nighthawks 1st              14.0           59.5
           2nd              16.5           59.5
Scouts     1st               2.5           66.0
           2nd               2.5           66.0

### Step 10. What is the number of observations in each regiment and company

In [39]:
regiment.groupby(['regiment', 'company']).size()

# size: 데이터의 총 수의 개수. DataFrame의 경우 '행의수 x 열의수'를 반환

regiment    company
Dragoons    1st        2
            2nd        2
Nighthawks  1st        2
            2nd        2
Scouts      1st        2
            2nd        2
dtype: int64

### Step 11. Iterate over a group and print the name and the whole data from the regiment

In [40]:
# Group the dataframe by regiment, and for each regiment,
for name, group in regiment.groupby('regiment'):
    # print the name of the regiment
    print(name)
    # print the data of that regiment
    print(group)

Dragoons
   regiment company    name  preTestScore  postTestScore
4  Dragoons     1st   Cooze             3             70
5  Dragoons     1st   Jacon             4             25
6  Dragoons     2nd  Ryaner            24             94
7  Dragoons     2nd    Sone            31             57
Nighthawks
     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
2  Nighthawks     2nd       Ali            31             57
3  Nighthawks     2nd    Milner             2             62
Scouts
   regiment company   name  preTestScore  postTestScore
8    Scouts     1st  Sloan             2             62
9    Scouts     1st  Piger             3             70
10   Scouts     2nd  Riani             2             62
11   Scouts     2nd    Ali             3             70